ADJUSTMENT_NEW_TABLE = '''
create table if not exists adjustment_new
(
    id            integer generated by default as identity
                    constraint adjustment_new_pk
                        primary key,
    wallet_id     integer
                    constraint adjustment_new_wallets_id_fk
                        references wallets,
    amount        integer,
    verified      text,
    description   text,
    status        text,
    color         text,
    creature_date timestamp
);

alter table adjustment_new
    owner to dok2412;
'''

ADJUSTMENT_OLL_TABLE = '''
create table if not exists adjustment_old
(
    id            integer generated by default as identity
                    constraint adjustment_old_pk
                        primary key,
    wallet_id     integer
                    constraint adjustment_old_wallets_id_fk
                        references wallets,
    amount        integer,
    verified      text,
    description   text,
    status        text,
    color         text,
    creature_date timestamp
);

alter table adjustment_old
    owner to dok2412;
'''

APPLICATIONS_TABLE = '''
create table if not exists applications
(
    id             integer not null
                    constraint applications_pk
                        primary key,
    type           text,
    operatoins_id  integer,
    description    text,
    courier        integer,
    creature_date  timestamp,
    execution_date timestamp,
    amounts        integer,
    currency       text,
    meeting_date   timestamp
);

alter table applications
    owner to dok2412;
'''

FROM_WALLET_TABLE = '''
create table if not exists from_wallets
(
    id            integer generated by default as identity
                    constraint from_wallets_pk
                        primary key,
    wallet_id     integer not null
                    constraint from_wallets_wallets_id_fk
                        references wallets,
    before        integer,
    amount        integer,
    after         integer,
    creature_date text,
    currency      text
);

alter table from_wallets
    owner to dok2412;
'''

OPERATIONS_TABLE = '''
create table if not exists operations
(
    id                integer generated by default as identity
                        constraint operations_pk
                            primary key,
    operations_id     text    not null,
    type_id           integer not null
                        constraint operations_operations_type_id_fk
                            references operations_type,
    creature_date     text    not null,
    description       text,
    user_id           integer not null
                        constraint operations_users_id_fk
                            references users,
    from_wallets_id   integer
                        constraint operations_from_wallets_id_fk
                            references from_wallets,
    to_wallets_id     integer
                        constraint operations_to_wallets_id_fk
                            references to_wallets,
    adjustment_oll_id integer
                        constraint operations_adjustment_oll_id_fk
                            references adjustment_old,
    adjustment_new_id integer
                        constraint operations_adjustment_new_id_fk
                            references adjustment_new,
    groups            text,
    applications_id   integer
                        constraint operations_applications_id_fk
                            references applications,
    write_id          integer
                        constraint operations_write_balance_id_fk
                            references write_balance
);

alter table operations
    owner to dok2412;
'''

OPERATION_TYPE_TABLE = '''
create table if not exists operations_type
(
    id   integer generated by default as identity
            constraint operations_type_pk
                primary key,
    type text
);

alter table operations_type
    owner to dok2412;
'''

TO_WALLET_TABLE = '''
create table if not exists to_wallets
(
    id            integer generated by default as identity
                    constraint to_wallets_pk
                        primary key,
    before        integer,
    amount        integer,
    after         integer,
    wallet_id     integer not null
                    constraint to_wallets_wallets_id_fk
                        references wallets,
    creature_date text,
    currency      text
);

alter table to_wallets
    owner to dok2412;
'''

USER_ROLE_TABLE = '''
create table if not exists user_role
(
    id   integer generated by default as identity
            constraint user_role_pk
                primary key,
    type text not null
);

alter table user_role
    owner to dok2412;
'''

USERS_TABLE = '''
--создание таблици профиля
create table if not exists users
(
    id            integer generated by default as identity
                    constraint users_pk
                        primary key,
    user_id       text    not null,
    first_name    text    not null,
    role          integer not null
                    constraint users_user_role_id_fk
                        references user_role,
    activity      boolean,
    creation_date timestamp,
    tg_id         text
);

alter table users
    owner to dok2412;
'''

WALLET_TABLE = '''
create table if not exists wallets
(
    id          integer generated by default as identity
                    constraint wallets_pk
                        primary key,
    wallet_id   text,
    holder_id   integer
                    constraint wallets_users_id_fk
                        references users,
    name        text,
    amount      integer,
    currency    text,
    active      boolean,
    pinned      boolean,
    pin_on_main boolean,
    verified    text,
    description text,
    status      text,
    show        text,
    color       text,
    detete      boolean default false,
    delete_date timestamp
);

alter table wallets
    owner to dok2412;
'''

WRITE_BALANCE_TABLE = '''
--создание таблици профиля
create table if not exists write_balance
(
    id        integer generated by default as identity
                constraint write_balance_pk
                    primary key,
    date      text,
    wallet_id integer
                constraint write_balance_wallets_id_fk
                    references wallets,
    amount    integer,
    currency  text
);

alter table write_balance
    owner to dok2412;
'''